// Generated by CoffeeScript 1.3.3
(function() {
  var feval, ode, rk, zeros,
    __slice = [].slice;

  rk = {};

  rk[1] = function(tn, tl, yl) {
    var fs, fv, h, i, _i, _len, _results;
    h = tn - tl;
    fv = feval(tl, yl);
    _results = [];
    for (i = _i = 0, _len = fv.length; _i < _len; i = ++_i) {
      fs = fv[i];
      _results.push(yl[i] + h * fs);
    }
    return _results;
  };

  rk[2] = function(tn, tl, yl) {
    var F1, F2, h;
    h = tn - tl;
    F1 = feval(tl, yl);
    F2 = feval(tl + h, yl + h * F1);
    return yl + (h / 2) * (F1 + F2);
  };

  rk[3] = function(tn, tl, yl) {
    var F1, F2, F3, h;
    h = tn - tl;
    F1 = feval(tl, yl);
    F2 = feval(tl + 0.5 * h, yl + 0.5 * h * F1);
    F3 = feval(tl + 0.75 * h, yl + 0.75 * h * F2);
    return yl + (h / 9) * (2 * F1 + 3 * F2 + 4 * F3);
  };

  rk[4] = function(tn, tl, yl) {
    var F1, F2, F3, F4, h;
    h = tn - tl;
    F1 = feval(tl, yl);
    F2 = feval(tl + 0.5 * h, yl + 0.5 * h * F1);
    F3 = feval(tl + 0.5 * h, yl + 0.5 * h * F2);
    F4 = feval(tn, yl + h * F3);
    return yl + (h / 6) * (F1 + 2 * F2 + 2 * F3 + F4);
  };

  zeros = function(m, n) {
    var _i, _results;
    _results = [];
    for (_i = 1; 1 <= m ? _i <= m : _i >= m; 1 <= m ? _i++ : _i--) {
      _results.push((function() {
        var _j, _results1;
        _results1 = [];
        for (_j = 1; 1 <= n ? _j <= n : _j >= n; 1 <= n ? _j++ : _j--) {
          _results1.push(0);
        }
        return _results1;
      })());
    }
    return _results;
  };

  feval = function(t, y) {};

  ode = function() {
    var L, N, Y, f, i, params, rk, ts, y0, _i;
    rk = arguments[0], f = arguments[1], ts = arguments[2], y0 = arguments[3], params = 5 <= arguments.length ? __slice.call(arguments, 4) : [];
    feval = function(ti, yi) {
      return f.apply(null, [ti, yi].concat(__slice.call(params)));
    };
    L = ts.length;
    N = y0.length;
    Y = zeros(L, N);
    Y[0] = y0;
    for (i = _i = 1; 1 <= L ? _i < L : _i > L; i = 1 <= L ? ++_i : --_i) {
      Y[i] = rk(ts[i], ts[i - 1], Y[i - 1]);
    }
    return Y;
  };

  $blab.ode = {
    rk: rk,
    ode: ode
  };

}).call(this);
